library(sp)
library(shapefiles)
library(maptools)
library(ggplot2)
library(plyr)
library(rgdal) 
gpclibPermit() 
#########################
suisse.map <- readOGR("/Users/raf/Desktop/carte/CHE_adm/", layer = "CHE_adm1") 
str(suisse.map)
Sys.setlocale("LC_ALL", locale="C") 
suisse.ggmap <- fortify(suisse.map, region="NAME_1") 
str(suisse.ggmap)
###marche pas ???####ggplot(suisse.ggmap,aes(x = long, y = lat))+geom_polygon()
states <- subset(suisse.ggmap, id %in% c( "Fribourg"),droplevels=TRUE2)
ggplot(suisse.ggmap, aes(long, lat))+ geom_polygon(aes(group=group), fill="black", colour="white", size=.3) + coord_map()
ggplot(states, aes(long, lat))+ geom_polygon(aes(group=group), fill="grey80", colour="white", size=.3) + coord_map()+theme_minimal()
str(states)

#########################
suisse.map <- readOGR("/Users/raf/Desktop/carte/CHE_adm/", layer = "CHE_adm2") 
str(suisse.map)
Sys.setlocale("LC_ALL", locale="C") 
suisse.ggmap <- fortify(suisse.map, region="NAME_2") 
str(suisse.ggmap)
###marche pas ???####ggplot(suisse.ggmap,aes(x = long, y = lat))+geom_polygon()
states <- subset(suisse.ggmap, id %in% c( "Fribourg"))
ggplot(suisse.ggmap, aes(long, lat))+ geom_polygon(aes(group=group), fill="grey", colour="white", size=.3) + coord_map()+theme_minimal()
ggplot(states, aes(long, lat))+ geom_polygon(aes(group=group), fill="grey80", colour="white", size=.3) + coord_map()+theme_minimal()
nom<-suisse.ggmap$group
incidence<-round(runif(204, min=0, max=1), digits=2)
merge(nom,incidence)